// Household "concepts" (needs) the app knows about. A need is more important than a SKU.
// Quantities are per 14 days for a household of 2 adults; scaled by household size.
import type { Flexibility, Level } from '../shared/types.ts';

export type Concept = {
  id: string;
  label: string;
  emoji: string;
  category: 'dairy' | 'eggs' | 'bakery' | 'meat' | 'fish' | 'pantry' | 'drinks' | 'snacks' | 'produce' | 'cleaning' | 'paper' | 'frozen' | 'kids';
  synonyms: string[]; // Hebrew words used in chat (singular/plural/colloquial)
  query: string; // what to type into a supermarket search
  mustInclude?: string[]; // product name must include one of these (filters search noise)
  exclude?: string[]; // product name must not include any of these
  alsoInclude?: string[]; // a second required word group (e.g. cola AND zero)
  prefer?: RegExp; // pack-size hint: names matching this rank higher (e.g. 6-pack cola)
  brands: string[]; // known brands, used to recognise "רק קוקה קולה" / "לא פפסי"
  stockUnit: string; // unit people talk in ("ביצים", "קופסאות")
  packLabel: string; // what one basket unit is
  packSize: number; // stock units per pack
  base14: number; // stock units per 14 days for 2 adults
  childFactor: number; // share of an adult a child consumes for this item
  wasteRisk: Level;
  shelfStable: boolean; // good for stocking up
  defaultFlex: Flexibility;
  dealSensitivity: Level;
  dairy?: boolean;
  meat?: boolean;
  staple?: boolean; // shown in onboarding chips
  parveByDefault?: boolean; // virtually always parve (Bamba) — no name marker needed
  dairyFree?: boolean; // the concept itself is dairy-free (product must look parve)
  kidItem?: boolean; // mainly for the child (child-only allergies apply)
  subGroup?: string; // needs that can stand in for each other when the household is flexible (e.g. chicken)
};

/** Words that indicate a product is dairy-free / parve. Used for hard dairy-free constraints. */
const PARVE_MARKERS_LIST = ['פרווה', 'פרוה', 'ללא חלב', 'ללא לקטוז ופרווה', 'טבעוני', 'סויה', 'אלפרו', 'שקדים', 'קוקוס', 'שיבולת', 'צמחי', 'vegan', 'parve'];

export const PARVE_MARKERS = PARVE_MARKERS_LIST;
const c = (x: Concept) => x;

export const CONCEPTS: Concept[] = [
  c({ id: 'EGGS', label: 'ביצים', emoji: '🥚', category: 'eggs', synonyms: ['ביצים', 'ביצה', 'תבנית ביצים'], query: 'ביצים L', mustInclude: ['ביצ'], exclude: ['שוקולד', 'פסטה', 'סלט', 'קינדר', 'הפתעה', 'ביצי שוקולד'], prefer: /12|L|M|גדולות|בינוניות/, brands: ['תנובה', 'יש מאיר', 'משק'], stockUnit: 'ביצים', packLabel: 'תבנית 12', packSize: 12, base14: 24, childFactor: 0.6, wasteRisk: 'medium', shelfStable: false, defaultFlex: 'category_flexible', dealSensitivity: 'medium', staple: true }),
  c({ id: 'BREAD', label: 'לחם', emoji: '🍞', category: 'bakery', synonyms: ['לחם', 'לחמים', 'כיכר'], query: 'לחם אחיד פרוס', mustInclude: ['לחם'], exclude: ['פירורי'], brands: ['אנג\'ל', 'ברמן', 'דגנית'], stockUnit: 'כיכרות', packLabel: 'כיכר', packSize: 1, base14: 4, childFactor: 0.5, wasteRisk: 'high', shelfStable: false, defaultFlex: 'brand_flexible', dealSensitivity: 'low', staple: true }),
  c({ id: 'TUNA', label: 'טונה', emoji: '🥫', category: 'pantry', synonyms: ['טונה', 'טונות', 'קופסאות טונה'], query: 'טונה בשמן', mustInclude: ['טונה'], exclude: ['סלט', 'פיצה'], prefer: /4\s*[*xX×]|רביעי|4\s*י/, brands: ['סטארקיסט', 'פטי', 'ויליגר', 'אחלה', 'מעדנות'], stockUnit: 'קופסאות', packLabel: 'רביעייה', packSize: 4, base14: 8, childFactor: 0.5, wasteRisk: 'low', shelfStable: true, defaultFlex: 'brand_flexible', dealSensitivity: 'high', staple: true }),
  c({ id: 'CREAM_CHEESE', label: 'גבינת שמנת', emoji: '🧀', category: 'dairy', synonyms: ['גבינת שמנת', 'גבינה לבנה', 'שמנת למריחה', 'פילדלפיה'], query: 'גבינת שמנת', mustInclude: ['שמנת'], exclude: ['חמוצה', 'מתוקה', 'לבישול', 'הקצפה', 'להקצפה', 'בישול'], brands: ['תנובה', 'שטראוס', 'פילדלפיה', 'גד', 'טרה'], stockUnit: 'גביעים', packLabel: 'גביע', packSize: 1, base14: 3, childFactor: 0.5, wasteRisk: 'medium', shelfStable: false, defaultFlex: 'brand_flexible', dealSensitivity: 'medium', dairy: true, staple: true }),
  c({ id: 'YELLOW_CHEESE', label: 'גבינה צהובה', emoji: '🧀', category: 'dairy', synonyms: ['גבינה צהובה', 'צהובה', 'עמק'], query: 'גבינה צהובה פרוסות', mustInclude: ['גבינה', 'עמק'], exclude: ['מגורדת'], brands: ['עמק', 'תנובה', 'גד', 'טרה'], stockUnit: 'אריזות', packLabel: 'אריזה', packSize: 1, base14: 2, childFactor: 0.5, wasteRisk: 'medium', shelfStable: false, defaultFlex: 'brand_flexible', dealSensitivity: 'medium', dairy: true, staple: true }),
  c({ id: 'MILK', label: 'חלב', emoji: '🥛', category: 'dairy', synonyms: ['חלב'], query: 'חלב 3% קרטון', mustInclude: ['חלב'], exclude: ['שוקו', 'אורז', 'סויה', 'שקדים', 'אבקת'], prefer: /1\s*ל|ליטר|קרטון/, brands: ['תנובה', 'טרה', 'יטבתה'], stockUnit: 'קרטונים', packLabel: 'קרטון ליטר', packSize: 1, base14: 4, childFactor: 1, wasteRisk: 'high', shelfStable: false, defaultFlex: 'category_flexible', dealSensitivity: 'low', dairy: true }),
  c({ id: 'COTTAGE', label: 'קוטג׳', emoji: '🥣', category: 'dairy', synonyms: ['קוטג', 'קוטג׳', 'קוטג\''], query: 'קוטג 5%', mustInclude: ['קוטג'], brands: ['תנובה', 'טרה', 'שטראוס'], stockUnit: 'גביעים', packLabel: 'גביע', packSize: 1, base14: 3, childFactor: 0.5, wasteRisk: 'medium', shelfStable: false, defaultFlex: 'brand_flexible', dealSensitivity: 'medium', dairy: true }),
  c({ id: 'KIDS_DAIRY', label: 'מעדנים לילד', emoji: '🍮', category: 'kids', synonyms: ['מעדנים', 'מעדן', 'מילקי', 'דני', 'יופלה'], query: 'מעדן חלב', mustInclude: ['מעדן', 'מילקי', 'דני', 'פודינג'], brands: ['שטראוס', 'תנובה', 'יופלה', 'מילקי', 'דני'], stockUnit: 'מעדנים', packLabel: 'מארז 4', packSize: 4, base14: 0, childFactor: 6, wasteRisk: 'medium', shelfStable: false, defaultFlex: 'brand_flexible', dealSensitivity: 'medium', dairy: true, staple: true, kidItem: true }),
  c({ id: 'COLA_ZERO', label: 'קולה זירו', emoji: '🥤', category: 'drinks', synonyms: ['קולה זירו', 'קוקה קולה זירו', 'קוקה זירו', 'זירו', 'קולה'], query: 'קוקה קולה זירו 1.5', mustInclude: ['קולה', 'פפסי', 'cola'], alsoInclude: ['זירו', 'zero', 'מקס', 'דיאט'], prefer: /6\s*[*xX×]|שישי/, exclude: ['פחית'], brands: ['קוקה קולה', 'פפסי', 'RC'], stockUnit: 'בקבוקים', packLabel: 'שישייה 1.5 ל׳', packSize: 6, base14: 6, childFactor: 0.3, wasteRisk: 'low', shelfStable: true, defaultFlex: 'exact_product', dealSensitivity: 'medium', staple: true }),
  c({ id: 'SODA', label: 'סודה', emoji: '🫧', category: 'drinks', synonyms: ['סודה', 'מים מוגזים'], query: 'סודה 1.5 ליטר', mustInclude: ['סודה', 'מוגזים'], prefer: /6\s*[*xX×]|שישי/, brands: ['מי עדן', 'נביעות', 'קריסטל'], stockUnit: 'בקבוקים', packLabel: 'שישייה', packSize: 6, base14: 6, childFactor: 0.3, wasteRisk: 'low', shelfStable: true, defaultFlex: 'category_flexible', dealSensitivity: 'high', staple: true }),
  c({ id: 'PEANUT_BUTTER', label: 'חמאת בוטנים', emoji: '🥜', category: 'pantry', synonyms: ['חמאת בוטנים'], query: 'חמאת בוטנים', mustInclude: ['בוטנים'], exclude: ['במבה', 'חטיף', 'שוקולד', 'קרימי ח'], brands: ['ביגי', 'של', 'גרין', 'סקיפי'], stockUnit: 'צנצנות', packLabel: 'צנצנת', packSize: 1, base14: 0.5, childFactor: 0.5, wasteRisk: 'low', shelfStable: true, defaultFlex: 'brand_flexible', dealSensitivity: 'medium', staple: true }),
  c({ id: 'CHOCO_SPREAD', label: 'ממרח שוקולד', emoji: '🍫', category: 'pantry', synonyms: ['ממרח שוקולד', 'נוטלה', 'השחר'], query: 'ממרח שוקולד', mustInclude: ['ממרח', 'נוטלה'], brands: ['השחר העולה', 'נוטלה', 'עלית'], stockUnit: 'צנצנות', packLabel: 'צנצנת', packSize: 1, base14: 0.5, childFactor: 0.6, wasteRisk: 'low', shelfStable: true, defaultFlex: 'brand_flexible', dealSensitivity: 'medium', staple: true, kidItem: true }),
  c({ id: 'PASTA', label: 'פסטה', emoji: '🍝', category: 'pantry', synonyms: ['פסטה', 'ספגטי', 'פנה', 'מקרוני'], query: 'פסטה 500 גרם', mustInclude: ['פסטה', 'ספגטי', 'פנה', 'פוזילי'], exclude: ['רוטב', 'ניוקי', 'ממולא', 'טורטליני', 'רביולי'], brands: ['אסם', 'ברילה', 'דה צ\'קו', 'בארילה'], stockUnit: 'חבילות', packLabel: 'חבילה 500 ג׳', packSize: 1, base14: 3, childFactor: 0.6, wasteRisk: 'low', shelfStable: true, defaultFlex: 'category_flexible', dealSensitivity: 'high', staple: true }),
  c({ id: 'PTITIM', label: 'פתיתים', emoji: '🍚', category: 'pantry', synonyms: ['פתיתים'], query: 'פתיתים', mustInclude: ['פתיתים'], brands: ['אסם'], stockUnit: 'חבילות', packLabel: 'חבילה', packSize: 1, base14: 1, childFactor: 0.6, wasteRisk: 'low', shelfStable: true, defaultFlex: 'brand_flexible', dealSensitivity: 'medium', staple: true }),
  c({ id: 'RICE', label: 'אורז', emoji: '🍚', category: 'pantry', synonyms: ['אורז'], query: 'אורז פרסי 1 ק"ג', mustInclude: ['אורז'], exclude: ['פריכיות', 'עוגיות', 'משקה'], brands: ['סוגת', 'מיה'], stockUnit: 'ק״ג', packLabel: 'שקית ק״ג', packSize: 1, base14: 1, childFactor: 0.5, wasteRisk: 'low', shelfStable: true, defaultFlex: 'category_flexible', dealSensitivity: 'high' }),
  c({ id: 'BAMBA', label: 'במבה', emoji: '🥜', category: 'snacks', synonyms: ['במבה', 'במבות'], query: 'במבה', mustInclude: ['במבה'], prefer: /4\s*[*xX×]|מארז|רביעי/, brands: ['אסם'], stockUnit: 'שקיות', packLabel: 'מארז', packSize: 4, base14: 4, childFactor: 1.5, wasteRisk: 'low', shelfStable: true, defaultFlex: 'exact_product', dealSensitivity: 'medium', staple: true, kidItem: true, parveByDefault: true }),
  c({ id: 'COFFEE', label: 'קפה', emoji: '☕', category: 'drinks', synonyms: ['קפה', 'נס קפה', 'קפה שחור', 'קפסולות'], query: 'קפה נמס', mustInclude: ['קפה', 'נס'], exclude: ['מכונת', 'ספל', 'קר', 'אייס', 'קפסול'], brands: ['עלית', 'נסקפה', 'טסטרס צ\'ויס', 'לנדוור'], stockUnit: 'צנצנות', packLabel: 'צנצנת', packSize: 1, base14: 0.7, childFactor: 0, wasteRisk: 'low', shelfStable: true, defaultFlex: 'brand_flexible', dealSensitivity: 'medium', staple: true }),
  c({ id: 'CHICKEN_BREAST', label: 'חזה עוף', emoji: '🍗', category: 'meat', synonyms: ['חזה עוף', 'חזה', 'שניצל', 'שניצלים'], query: 'חזה עוף טרי', mustInclude: ['חזה'], exclude: ['הודו', 'מעושן', 'נקניק'], brands: ['עוף טוב', 'מאמא עוף', 'זוגלובק', 'יסעור'], stockUnit: 'ק״ג', packLabel: 'ק״ג', packSize: 1, base14: 1.5, childFactor: 0.5, wasteRisk: 'medium', shelfStable: false, defaultFlex: 'brand_flexible', dealSensitivity: 'high', meat: true, subGroup: 'chicken', staple: true }),
  c({ id: 'CHICKEN_THIGHS', label: 'פרגיות', emoji: '🍗', category: 'meat', synonyms: ['פרגיות', 'פרגית', 'ירכיים'], query: 'פרגיות עוף', mustInclude: ['פרגי', 'ירך'], exclude: ['נקניק'], brands: ['עוף טוב', 'מאמא עוף', 'זוגלובק', 'יסעור'], stockUnit: 'ק״ג', packLabel: 'ק״ג', packSize: 1, base14: 1, childFactor: 0.5, wasteRisk: 'medium', shelfStable: false, defaultFlex: 'brand_flexible', dealSensitivity: 'high', meat: true, subGroup: 'chicken' }),
  c({ id: 'GROUND_MEAT', label: 'בשר טחון', emoji: '🥩', category: 'meat', synonyms: ['בשר טחון', 'טחון', 'בשר'], query: 'בשר בקר טחון', mustInclude: ['טחון'], exclude: ['קציצות'], brands: ['טיב טעם', 'זוגלובק', 'אדום אדום'], stockUnit: 'ק״ג', packLabel: '500 ג׳', packSize: 0.5, base14: 1, childFactor: 0.5, wasteRisk: 'medium', shelfStable: false, defaultFlex: 'category_flexible', dealSensitivity: 'high', meat: true, staple: true }),
  c({ id: 'SALMON', label: 'סלמון', emoji: '🐟', category: 'fish', synonyms: ['סלמון'], query: 'פילה סלמון', mustInclude: ['סלמון'], exclude: ['מעושן', 'סושי'], brands: ['דג', 'מעדני הים'], stockUnit: 'ק״ג', packLabel: '500 ג׳', packSize: 0.5, base14: 0.5, childFactor: 0.4, wasteRisk: 'high', shelfStable: false, defaultFlex: 'category_flexible', dealSensitivity: 'high', staple: true }),
  c({ id: 'SCHNITZEL_FROZEN', label: 'שניצל קפוא', emoji: '🧊', category: 'frozen', synonyms: ['שניצל קפוא', 'תירס שניצל', 'שניצלונים'], query: 'שניצל קפוא', mustInclude: ['שניצל'], brands: ['מאמא עוף', 'זוגלובק', 'טבעול', 'עוף טוב'], stockUnit: 'אריזות', packLabel: 'אריזה', packSize: 1, base14: 1, childFactor: 0.6, wasteRisk: 'low', shelfStable: true, defaultFlex: 'brand_flexible', dealSensitivity: 'high' }),
  c({ id: 'HUMMUS', label: 'חומוס', emoji: '🫘', category: 'dairy', synonyms: ['חומוס'], query: 'חומוס', mustInclude: ['חומוס'], exclude: ['גרגרי', 'יבש'], brands: ['צבר', 'אחלה', 'שטראוס'], stockUnit: 'גביעים', packLabel: 'גביע', packSize: 1, base14: 2, childFactor: 0.5, wasteRisk: 'medium', shelfStable: false, defaultFlex: 'brand_flexible', dealSensitivity: 'medium' }),
  c({ id: 'TOMATOES', label: 'עגבניות', emoji: '🍅', category: 'produce', synonyms: ['עגבניות', 'עגבנייה', 'עגבניה'], query: 'עגבניות', mustInclude: ['עגבני'], exclude: ['רסק', 'רוטב', 'מיובשות', 'שרי', 'קוביות', 'מרוסקות', 'שימורי', 'מקולפות', 'שימורים', 'מיובש'], brands: [], stockUnit: 'ק״ג', packLabel: 'ק״ג', packSize: 1, base14: 2, childFactor: 0.4, wasteRisk: 'high', shelfStable: false, defaultFlex: 'category_flexible', dealSensitivity: 'low', staple: true }),
  c({ id: 'CUCUMBERS', label: 'מלפפונים', emoji: '🥒', category: 'produce', synonyms: ['מלפפונים', 'מלפפון'], query: 'מלפפון', mustInclude: ['מלפפון'], exclude: ['חמוץ', 'כבוש', 'במלח', 'פריניר', 'חמוצים'], brands: [], stockUnit: 'ק״ג', packLabel: 'ק״ג', packSize: 1, base14: 2, childFactor: 0.5, wasteRisk: 'high', shelfStable: false, defaultFlex: 'category_flexible', dealSensitivity: 'low', staple: true }),
  c({ id: 'ONIONS', label: 'בצל', emoji: '🧅', category: 'produce', synonyms: ['בצל', 'בצלים'], query: 'בצל יבש', mustInclude: ['בצל'], exclude: ['ירוק', 'מטוגן', 'אבקת', 'קרם', 'מרק', 'שום'], brands: [], stockUnit: 'ק״ג', packLabel: 'ק״ג', packSize: 1, base14: 1.5, childFactor: 0.3, wasteRisk: 'low', shelfStable: false, defaultFlex: 'category_flexible', dealSensitivity: 'low', staple: true }),
  c({ id: 'CABBAGE', label: 'כרוב', emoji: '🥬', category: 'produce', synonyms: ['כרוב'], query: 'כרוב לבן', mustInclude: ['כרוב'], exclude: ['כבוש', 'סלט', 'חמוץ', 'ניצני', 'קולסלאו'], brands: [], stockUnit: 'יח׳', packLabel: 'ראש כרוב', packSize: 1, base14: 1, childFactor: 0.3, wasteRisk: 'medium', shelfStable: false, defaultFlex: 'category_flexible', dealSensitivity: 'low', staple: true }),
  c({ id: 'LETTUCE', label: 'חסה', emoji: '🥬', category: 'produce', synonyms: ['חסה', 'חסות'], query: 'חסה', mustInclude: ['חסה', 'חסת'], exclude: ['סלט', 'רוטב'], brands: [], stockUnit: 'יח׳', packLabel: 'חסה', packSize: 1, base14: 2, childFactor: 0.3, wasteRisk: 'high', shelfStable: false, defaultFlex: 'category_flexible', dealSensitivity: 'low', staple: true }),
  c({ id: 'KOHLRABI', label: 'קולרבי', emoji: '🥗', category: 'produce', synonyms: ['קולרבי'], query: 'קולרבי', mustInclude: ['קולרבי'], brands: [], stockUnit: 'ק״ג', packLabel: 'ק״ג', packSize: 1, base14: 1, childFactor: 0.3, wasteRisk: 'medium', shelfStable: false, defaultFlex: 'category_flexible', dealSensitivity: 'low', staple: true }),
  c({ id: 'DAIRY_FREE_DESSERT', label: 'מעדנים ללא חלב', emoji: '🍮', category: 'kids', synonyms: ['מעדנים ללא חלב', 'מעדן ללא חלב', 'מעדן פרווה', 'מעדנים פרווה', 'מעדני סויה', 'מעדן סויה', 'קינוח פרווה'], query: 'מעדן סויה', mustInclude: ['מעדן', 'פודינג', 'קינוח', 'יוגורט'], alsoInclude: PARVE_MARKERS_LIST, brands: ['אלפרו', 'טבעול', 'יופלה'], stockUnit: 'מעדנים', packLabel: 'מארז 4', packSize: 4, base14: 0, childFactor: 6, wasteRisk: 'medium', shelfStable: false, defaultFlex: 'brand_flexible', dealSensitivity: 'medium', dairyFree: true, kidItem: true, staple: true }),
  c({ id: 'BANANAS', label: 'בננות', emoji: '🍌', category: 'produce', synonyms: ['בננות', 'בננה'], query: 'בננה', mustInclude: ['בננ'], exclude: ['חטיף', 'יוגורט', 'מעדן'], brands: [], stockUnit: 'ק״ג', packLabel: 'ק״ג', packSize: 1, base14: 1.5, childFactor: 0.8, wasteRisk: 'high', shelfStable: false, defaultFlex: 'category_flexible', dealSensitivity: 'low' }),
  c({ id: 'FRUIT_FOR_CHILD', label: 'פרי עונתי', emoji: '🍎', category: 'produce', synonyms: ['פרי', 'פירות', 'תפוחים', 'פרי לילד'], query: 'תפוח עץ', mustInclude: ['תפוח', 'אגס', 'ענבים', 'תותים', 'קלמנטינה', 'אפרסק'], exclude: ['מיץ', 'אדמה', 'רסק'], brands: [], stockUnit: 'ק״ג', packLabel: 'ק״ג', packSize: 1, base14: 0, childFactor: 1.5, wasteRisk: 'high', shelfStable: false, defaultFlex: 'exploratory', staple: true, dealSensitivity: 'high' }),
  c({ id: 'OIL', label: 'שמן', emoji: '🫒', category: 'pantry', synonyms: ['שמן', 'שמן קנולה', 'שמן זית'], query: 'שמן קנולה 1 ליטר', mustInclude: ['שמן'], exclude: ['תינוק', 'מנוע', 'בשמן'], brands: ['עץ הזית', 'שמן', 'מזרע'], stockUnit: 'בקבוקים', packLabel: 'בקבוק', packSize: 1, base14: 0.5, childFactor: 0.3, wasteRisk: 'low', shelfStable: true, defaultFlex: 'category_flexible', dealSensitivity: 'high' }),
  c({ id: 'BUTTER', label: 'חמאה', emoji: '🧈', category: 'dairy', synonyms: ['חמאה'], query: 'חמאה 200 גרם', mustInclude: ['חמאה'], exclude: ['בוטנים', 'עוגיות'], brands: ['תנובה', 'טרה'], stockUnit: 'חבילות', packLabel: 'חבילה', packSize: 1, base14: 1, childFactor: 0.4, wasteRisk: 'low', shelfStable: false, defaultFlex: 'category_flexible', dealSensitivity: 'medium', dairy: true }),
  c({ id: 'CEREAL', label: 'דגני בוקר', emoji: '🥣', category: 'pantry', synonyms: ['דגני בוקר', 'קורנפלקס', 'כריות'], query: 'דגני בוקר', mustInclude: ['דגני', 'קורנפלקס', 'כריות'], brands: ['תלמה', 'נסטלה', 'קלוגס'], stockUnit: 'קופסאות', packLabel: 'קופסה', packSize: 1, base14: 1, childFactor: 1, wasteRisk: 'low', shelfStable: true, defaultFlex: 'brand_flexible', dealSensitivity: 'high' }),
  c({ id: 'SNACK_ROTATING', label: 'חטיף מתחלף', emoji: '🍪', category: 'snacks', synonyms: ['חטיף', 'חטיפים', 'עוגיות'], query: 'חטיף', mustInclude: ['חטיף', 'עוגיות', 'ופל', 'ביסלי', 'צ\'יטוס'], brands: ['אסם', 'עלית', 'שטראוס'], stockUnit: 'חבילות', packLabel: 'חבילה', packSize: 1, base14: 2, childFactor: 1, wasteRisk: 'low', shelfStable: true, defaultFlex: 'exploratory', dealSensitivity: 'high' }),
  c({ id: 'TOILET_PAPER', label: 'נייר טואלט', emoji: '🧻', category: 'paper', synonyms: ['נייר טואלט', 'טואלט', 'נייר'], query: 'נייר טואלט 32', mustInclude: ['טואלט'], prefer: /32|30|24/, brands: ['לילי', 'סנו', 'טישו'], stockUnit: 'גלילים', packLabel: 'חבילת 32', packSize: 32, base14: 12, childFactor: 0.6, wasteRisk: 'low', shelfStable: true, defaultFlex: 'category_flexible', dealSensitivity: 'high' }),
  c({ id: 'LAUNDRY_DETERGENT', label: 'ג׳ל כביסה', emoji: '🧺', category: 'cleaning', synonyms: ['ג\'ל כביסה', 'גל כביסה', 'אבקת כביסה', 'נוזל כביסה', 'כביסה'], query: 'ג\'ל כביסה', mustInclude: ['כביסה'], exclude: ['מרכך', 'סל', 'מתקן'], brands: ['סנו', 'אריאל', 'פרסיל', 'בדין'], stockUnit: 'בקבוקים', packLabel: 'בקבוק', packSize: 1, base14: 0.5, childFactor: 0.4, wasteRisk: 'low', shelfStable: true, defaultFlex: 'brand_flexible', staple: true, dealSensitivity: 'high' }),
  c({ id: 'LAUNDRY_SOFTENER', label: 'מרכך כביסה', emoji: '🧴', category: 'cleaning', synonyms: ['מרכך כביסה', 'מרכך', 'מרככים'], query: 'מרכך כביסה', mustInclude: ['מרכך'], exclude: ['שיער', 'מים'], brands: ['בדין', 'סנו', 'קוטקס', 'לנור', 'מקסימה'], stockUnit: 'בקבוקים', packLabel: 'בקבוק', packSize: 1, base14: 0.5, childFactor: 0.4, wasteRisk: 'low', shelfStable: true, defaultFlex: 'brand_flexible', staple: true, dealSensitivity: 'high' }),
  c({ id: 'VANISH', label: 'ווניש / קליה', emoji: '✨', category: 'cleaning', synonyms: ['ווניש', 'וניש', 'קליה', 'vanish', 'מסיר כתמים'], query: 'וניש', mustInclude: ['וניש', 'ווניש', 'כתמים', 'קליה', 'vanish'], brands: ['וניש', 'סנו'], stockUnit: 'אריזות', packLabel: 'אריזה', packSize: 1, base14: 0.3, childFactor: 0.5, wasteRisk: 'low', shelfStable: true, defaultFlex: 'brand_flexible', staple: true, dealSensitivity: 'high' }),
  c({ id: 'DISH_SOAP', label: 'סבון כלים', emoji: '🧽', category: 'cleaning', synonyms: ['סבון כלים', 'נוזל כלים', 'פיירי', 'סבון'], query: 'סבון כלים', mustInclude: ['כלים'], exclude: ['מדיח', 'מברשת'], brands: ['פיירי', 'סנו', 'פלמוליב'], stockUnit: 'בקבוקים', packLabel: 'בקבוק', packSize: 1, base14: 0.5, childFactor: 0.3, wasteRisk: 'low', shelfStable: true, defaultFlex: 'category_flexible', dealSensitivity: 'high' }),
];

export const conceptById = new Map(CONCEPTS.map((x) => [x.id, x]));

export function defaultTypical14(concept: Concept, adults: number, kids: number): number {
  const scale = adults / 2 + (kids * concept.childFactor) / 2;
  const base = concept.base14 === 0 && kids > 0 ? concept.childFactor * kids : concept.base14 * scale;
  return Math.max(concept.packSize > 1 ? concept.packSize / 2 : 0.5, round1(base));
}

export function round1(n: number) {
  return Math.round(n * 10) / 10;
}

/** A concept for something the household added that we don't know. */
export function customConcept(id: string, label: string): Concept {
  return {
    id, label, emoji: '🛒', category: 'pantry', synonyms: [label], query: label, brands: [],
    stockUnit: 'יח׳', packLabel: 'יח׳', packSize: 1, base14: 1, childFactor: 0.3, wasteRisk: 'medium',
    shelfStable: false, defaultFlex: 'brand_flexible', dealSensitivity: 'medium',
  };
}
